import type { Session, Issue } from '../core/types.ts';

export class ReportGenerator {
    static async generateMarkdown(session: Session): Promise<string> {
        const duration = this.formatDuration(session.startTime, session.endTime || Date.now());
        const counts = this.getIssueCounts(session.issues);

        let md = `# 🧪 TestPilot Session Report\n\n`;
        md += `**Session ID:** \`${session.sessionId}\`\n\n`;
        md += `**Duration:** ${duration}\n\n`;
        md += `**Started:** ${new Date(session.startTime).toLocaleString()}\n\n`;
        if (session.endTime) {
            md += `**Ended:** ${new Date(session.endTime).toLocaleString()}\n\n`;
        }
        md += `---\n\n`;

        // Summary
        md += `## 📊 Summary\n\n`;
        md += `- **Total Issues:** ${session.issues.length}\n`;
        md += `- **Critical:** ${counts.critical} 🔴\n`;
        md += `- **High:** ${counts.high} 🟠\n`;
        md += `- **Medium:** ${counts.medium} 🟡\n`;
        md += `- **Low:** ${counts.low} ⚪\n\n`;

        if (counts.critical > 0) {
            md += `> ⚠️ **${counts.critical} CRITICAL ISSUE${counts.critical > 1 ? 'S' : ''} DETECTED** - Immediate attention required!\n\n`;
        }

        md += `---\n\n`;

        // Release Blockers
        const criticalIssues = session.issues.filter(i => i.level === 'critical');
        if (criticalIssues.length > 0) {
            md += `## 🚨 Release Blockers (Critical)\n\n`;
            criticalIssues.forEach((issue, idx) => {
                md += this.formatIssue(issue, idx + 1);
            });
            md += `---\n\n`;
        }

        // High Priority Issues
        const highIssues = session.issues.filter(i => i.level === 'high');
        if (highIssues.length > 0) {
            md += `## 🔴 High Priority Issues\n\n`;
            highIssues.forEach((issue, idx) => {
                md += this.formatIssue(issue, idx + 1);
            });
            md += `---\n\n`;
        }

        // Medium Priority Issues
        const mediumIssues = session.issues.filter(i => i.level === 'medium');
        if (mediumIssues.length > 0) {
            md += `## 🟡 Medium Priority Issues\n\n`;
            mediumIssues.forEach((issue, idx) => {
                md += this.formatIssue(issue, idx + 1);
            });
            md += `---\n\n`;
        }

        // Timeline
        md += `## ⏱️ Timeline\n\n`;
        const sortedIssues = [...session.issues].sort((a, b) => a.firstSeen - b.firstSeen);
        sortedIssues.forEach(issue => {
            const time = new Date(issue.firstSeen).toLocaleTimeString();
            const icon = this.getIcon(issue.level);
            md += `- **${time}** ${icon} ${issue.type.replace(/_/g, ' ').toUpperCase()}`;
            if (issue.occurrences > 1) {
                md += ` (×${issue.occurrences})`;
            }
            md += `\n  - ${issue.message}\n`;
        });

        md += `\n---\n\n`;
        md += `*Generated by TestPilot on ${new Date().toLocaleString()}*\n`;

        return md;
    }

    private static formatIssue(issue: Issue, index: number): string {
        let md = `### ${index}. ${issue.type.replace(/_/g, ' ').toUpperCase()}\n\n`;
        md += `**Message:** ${issue.message}\n\n`;

        if (issue.file) {
            md += `**Location:** \`${issue.file}`;
            if (issue.line) md += `:${issue.line}`;
            if (issue.column) md += `:${issue.column}`;
            md += `\`\n\n`;
        }

        md += `**URL:** ${issue.url}\n\n`;
        md += `**Occurrences:** ${issue.occurrences}\n\n`;
        md += `**First Seen:** ${new Date(issue.firstSeen).toLocaleString()}\n\n`;

        if (issue.occurrences > 1) {
            md += `**Last Seen:** ${new Date(issue.lastSeen).toLocaleString()}\n\n`;
        }

        if (issue.stackTrace) {
            md += `**Stack Trace:**\n\`\`\`\n${issue.stackTrace.substring(0, 500)}\n\`\`\`\n\n`;
        }

        if (issue.metadata && Object.keys(issue.metadata).length > 0) {
            md += `**Metadata:**\n\`\`\`json\n${JSON.stringify(issue.metadata, null, 2)}\n\`\`\`\n\n`;
        }

        return md;
    }

    private static formatDuration(start: number, end: number): string {
        const durationMs = end - start;
        const seconds = Math.floor(durationMs / 1000);
        const minutes = Math.floor(seconds / 60);
        const hours = Math.floor(minutes / 60);

        if (hours > 0) return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
        if (minutes > 0) return `${minutes}m ${seconds % 60}s`;
        return `${seconds}s`;
    }

    private static getIssueCounts(issues: Issue[]) {
        return {
            critical: issues.filter(i => i.level === 'critical').length,
            high: issues.filter(i => i.level === 'high').length,
            medium: issues.filter(i => i.level === 'medium').length,
            low: issues.filter(i => i.level === 'low').length,
        };
    }

    private static getIcon(level: string): string {
        switch (level) {
            case 'critical': return '🔴';
            case 'high': return '🟠';
            case 'medium': return '🟡';
            case 'low': return '⚪';
            default: return '⚫';
        }
    }
}
